[tool.poetry]
name = "deep-learning-finetuning-and-merge"
version = "0.1.0"
description = ""
authors = ["magnusgp <s204075@student.dtu.dk>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"

pybind11="^2.12"
kagglehub = "*"
pandas = "*"
pillow = "*"
torch = "2.1.2"
loguru = "*"
numpy = "<2"
transformers = "*"
peft = "*"
wandb = "*"
tqdm = "*"
matplotlib = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
